CREATE TABLE IF NOT EXISTS SEXO (
    ID SERIAL PRIMARY KEY,
    DESCRICAO VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS ESTADO (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(100),
    SIGLA VARCHAR(2)
);

CREATE TABLE IF NOT EXISTS CIDADE (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(100),
    ID_ESTADO INT NOT NULL,
    CONSTRAINT FK_CIDADE_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID)
);

CREATE TABLE IF NOT EXISTS BAIRRO (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(100),
    ID_CIDADE INT NOT NULL,
    CONSTRAINT FK_BAIRRO_CIDADE FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE(ID)
);

CREATE TABLE IF NOT EXISTS ENDERECO (
    ID SERIAL PRIMARY KEY,
    ID_BAIRRO INT NOT NULL,
    RUA VARCHAR(255),
    NUMERO VARCHAR(20),
    CEP VARCHAR(20),
    CONSTRAINT FK_ENDERECO_BAIRRO FOREIGN KEY (ID_BAIRRO) REFERENCES BAIRRO(ID)
);

CREATE TABLE IF NOT EXISTS ESPECIE (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS CLASSE (
    ID SERIAL PRIMARY KEY,
    ID_ESPECIE INT NOT NULL,
    NOME VARCHAR(255),
    CONSTRAINT FK_CLASSE_ESPECIE FOREIGN KEY (ID_ESPECIE) REFERENCES ESPECIE(ID)
);

CREATE TABLE IF NOT EXISTS PESSOA (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(80) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    ID_SEXO INT,
    ID_ENDERECO INT,
    EMAIL VARCHAR(200) UNIQUE,
    CPF BIGINT UNIQUE,
    TELEFONE INTEGER,
    CONSTRAINT FK_SEXO_PESSOA FOREIGN KEY (ID_SEXO) REFERENCES SEXO(ID),
    CONSTRAINT FK_ENDERECO_PESSOA FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO(ID),
    CONSTRAINT CHK_IDADE_MINIMA CHECK (EXTRACT(YEAR FROM AGE(CURRENT_DATE, DATA_NASCIMENTO)) >= 16)
);

CREATE TABLE IF NOT EXISTS FUNCIONARIO (
    ID SERIAL PRIMARY KEY,
    ID_PESSOA INTEGER NOT NULL,
    SALARIO NUMERIC(10, 2),
    DATA_ADMISSAO DATE,
    CONSTRAINT FK_PESSOA_FUNCIONARIO FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA(ID),
    CONSTRAINT CK_SALARIO_ATENDENTE CHECK (SALARIO BETWEEN 2000 AND 40000)
);

CREATE TABLE IF NOT EXISTS ATENDENTE (
    ID SERIAL PRIMARY KEY,
    ID_FUNCIONARIO INTEGER NOT NULL,
    QTD_ATENDIMENTOS INTEGER,
    CONSTRAINT FK_FUNCIONARIO_ATENDENTE FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID)
);

CREATE TABLE IF NOT EXISTS VETERINARIO (
    ID SERIAL PRIMARY KEY,
    ID_FUNCIONARIO INTEGER NOT NULL,
    ESPECIALIDADE VARCHAR(255),
    CRMV VARCHAR(50),
    CONSTRAINT FK_FUNCIONARIO_VETERINARIO FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID)
);

CREATE TABLE IF NOT EXISTS PROGRAMA_FIDELIDADE (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(255),
    DESCRICAO TEXT,
    DATA_INICIO DATE,
    DATA_FIM DATE
);

CREATE TABLE IF NOT EXISTS CLIENTE (
    ID SERIAL PRIMARY KEY,
    ID_PESSOA INTEGER NOT NULL,
    ID_ENDERECO INTEGER,
    ID_PROGRAMA INTEGER,
    CONSTRAINT FK_CLIENTE_PESSOA FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA(ID),
    CONSTRAINT FK_CLIENTE_ENDERECO FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO(ID),
    CONSTRAINT FK_CLIENTE_PROGRAMA FOREIGN KEY (ID_PROGRAMA) REFERENCES PROGRAMA_FIDELIDADE(ID)
);

CREATE TABLE IF NOT EXISTS ANIMAL (
    ID SERIAL PRIMARY KEY,
    ID_SEXO INT,
    ID_CLASSE INT,
    ID_CLIENTE INTEGER NOT NULL,
    NOME VARCHAR(255),
    DATA_NASCIMENTO DATE,
    PESO NUMERIC(5, 2),
    CONSTRAINT FK_SEXO_ANIMAL FOREIGN KEY (ID_SEXO) REFERENCES SEXO(ID),
    CONSTRAINT FK_CLASSE_ANIMAL FOREIGN KEY (ID_CLASSE) REFERENCES CLASSE(ID),
    CONSTRAINT FK_ANIMAL_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID)
);

CREATE TABLE IF NOT EXISTS ATENDIMENTO (
    ID SERIAL PRIMARY KEY,
    ID_ATENDENTE INTEGER NOT NULL,
    ID_VETERINARIO INTEGER NOT NULL,
    ID_ANIMAL INTEGER NOT NULL,
    TIPO_ATENDIMENTO VARCHAR(100),
    VALOR NUMERIC(10, 2),
    DATA_ATENDIMENTO DATE,
    TEXTO_CONSULTA TEXT,
    CONSTRAINT FK_ATENDIMENTO_VETERINARIO FOREIGN KEY (ID_VETERINARIO) REFERENCES VETERINARIO(ID),
    CONSTRAINT FK_ATENDIMENTO_ATENDENTE FOREIGN KEY (ID_ATENDENTE) REFERENCES ATENDENTE(ID),
    CONSTRAINT FK_ATENDIMENTO_ANIMAL FOREIGN KEY (ID_ANIMAL) REFERENCES ANIMAL(ID)
);

CREATE TABLE IF NOT EXISTS PEDIDO (
    ID SERIAL PRIMARY KEY,
    ID_CLIENTE INTEGER NOT NULL,
    ID_ATENDENTE INTEGER NOT NULL,
    DATA_PEDIDO DATE,
    STATUS VARCHAR(50),
    CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID),
    CONSTRAINT FK_PEDIDO_ATENDENTE FOREIGN KEY (ID_ATENDENTE) REFERENCES ATENDENTE(ID)
);

CREATE TABLE IF NOT EXISTS PRODUTO (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(255),
    MARCA VARCHAR(255),
    PRECO NUMERIC(10, 2),
    ESTOQUE INTEGER
);

CREATE TABLE IF NOT EXISTS PRODUTO_PEDIDO (
    ID SERIAL PRIMARY KEY,
    ID_PEDIDO INTEGER NOT NULL,
    ID_PRODUTO INTEGER NOT NULL,
    QUANTIDADE INTEGER,
    VALOR_TOTAL NUMERIC(10, 2),
    CONSTRAINT FK_PP_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID),
    CONSTRAINT FK_PP_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID)
);

CREATE TABLE IF NOT EXISTS NOTA_FISCAL (
    ID SERIAL PRIMARY KEY,
    ID_PRODUTO_PEDIDO INTEGER NOT NULL,
    DATA_EMISSAO DATE,
    NUMERO_SERIE VARCHAR(50),
    CONSTRAINT FK_NF_PRODUTO_PEDIDO FOREIGN KEY (ID_PRODUTO_PEDIDO) REFERENCES PRODUTO_PEDIDO(ID)
);

CREATE TABLE IF NOT EXISTS NIVEL_FIDELIDADE (
    ID SERIAL PRIMARY KEY,
    ID_PROGRAMA INTEGER NOT NULL,
    NOME VARCHAR(255),
    PONTOS_MINIMOS INTEGER,
    PONTOS_MAXIMOS INTEGER,
    MULTIPLICADOR_PONTOS NUMERIC(5, 2),
    CONSTRAINT FK_NIVEL_PROGRAMA FOREIGN KEY (ID_PROGRAMA) REFERENCES PROGRAMA_FIDELIDADE(ID)
);

CREATE TABLE IF NOT EXISTS BENEFICIO (
    ID SERIAL PRIMARY KEY,
    ID_NIVEL INTEGER NOT NULL,
    TIPO VARCHAR(255),
    VALOR_DESCONTO NUMERIC(10, 2),
    DESCRICAO VARCHAR(255),
    CONSTRAINT FK_BENEFICIO_NIVEL FOREIGN KEY (ID_NIVEL) REFERENCES NIVEL_FIDELIDADE(ID)
);

CREATE TABLE IF NOT EXISTS PONTOS_TRANSACAO (
    ID SERIAL PRIMARY KEY,
    ID_CLIENTE INTEGER NOT NULL,
    ID_PEDIDO INTEGER,
    ID_ATENDIMENTO INTEGER,
    PONTOS_GANHOS INTEGER,
    DATA_TRANSACAO DATE,
    TIPO_ORIGEM VARCHAR(100),
    CONSTRAINT FK_PONTOS_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID),
    CONSTRAINT FK_PONTOS_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID),
    CONSTRAINT FK_PONTOS_ATENDIMENTO FOREIGN KEY (ID_ATENDIMENTO) REFERENCES ATENDIMENTO(ID)
);

CREATE TABLE IF NOT EXISTS RESGATE_BENEFICIO (
    ID SERIAL PRIMARY KEY,
    ID_CLIENTE INTEGER NOT NULL,
    ID_BENEFICIO INTEGER NOT NULL,
    DATA_RESGATE DATE,
    STATUS VARCHAR(50),
    CONSTRAINT FK_RESGATE_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID),
    CONSTRAINT FK_RESGATE_BENEFICIO FOREIGN KEY (ID_BENEFICIO) REFERENCES BENEFICIO(ID)
);

CREATE TABLE IF NOT EXISTS AVALIACAO_DESEMPENHO (
    ID SERIAL PRIMARY KEY,
    ID_FUNCIONARIO INTEGER NOT NULL,
    MES INTEGER,
    ANO INTEGER,
    ATENDIMENTOS_MES INTEGER,
    SATISFACAO_MEDIA NUMERIC(5, 2),
    PONTUALIDADE NUMERIC(5, 2),
    PONTUACAO_TOTAL INTEGER,
    OBSERVACOES TEXT,
    CONSTRAINT FK_AVALIACAO_FUNCIONARIO FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID)
);

CREATE TABLE IF NOT EXISTS BONUS_MENSAL (
    ID SERIAL PRIMARY KEY,
    ID_AVALIACAO INTEGER NOT NULL,
    VALOR_BONUS NUMERIC(10, 2),
    DATA_PAGAMENTO DATE,
    STATUS VARCHAR(50),
    CONSTRAINT FK_BONUS_AVALIACAO FOREIGN KEY (ID_AVALIACAO) REFERENCES AVALIACAO_DESEMPENHO(ID)
);
